### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Samuell1** [seriallos/commandstar#23]
TypeError: Cannot read property 'dataPath' of undefined
  at Object.<anonymous> (/home/vps/Desktop/commandstar/lib/commandstar.coffee:54:5, <js>:70:33)
  at Object.<anonymous> (/home/vps/Desktop/commandstar/lib/commandstar.coffee:1:1, <js>:311:4)
  at Module._compile (module.js:456:26)

My config:
```
starbound:
  binPath: /home/vps/Desktop/Starbound/starbound
  assetsPath: /home/vps/Desktop/Starbound/assets
  dataPath: /home/vps/Desktop/Starbound/universe
  logFile: /home/vps/Desktop/Starbound/starbound_server.log
  configFile: /home/vps/Desktop/Starbound/starbound.config
```
